In [15]:
import numpy as np





CHESS_SYMBOLS_ENG = {
    "r": "♖", "R": "♜",
    "s": "♘", "S": "♞",
    "b": "♗", "B": "♝",
    "q": "♕", "Q": "♛",
    "k": "♔", "K": "♚",
    "p": "♙", "P": "♟",
}


position = [['r','n','b','q','k','b','n','r'],
            ['p','p','p','p','p','p','p','p'],
            ['.','.','.','.','.','.','.','.'],
            ['.','.','.','.','.','.','.','.'],
            ['.','.','.','.','.','.','.','.'],
            ['.','.','.','.','.','.','.','.'],
            ['P','P','P','P','P','P','P','P'],
            ['R','N','B','Q','K','B','N','R']]


star_left =        [['a1'],         #CGA 1AVOIDING ROTATED BITBOARDS WITH DIRECT LOOKUPSam Tannous1Durham, North Carolina, USA
                 ['b1','a2'],       #https://arxiv.org/pdf/0704.3773.pdf
               ['c1','b2','a3'],
            ['d1','c2','b3','a4'],
          ['e1','d2','c3','b4','a5'],
       ['f1','e2','d3','c4','b5','a6'],
     ['g1','f2','e3','d4','c5','b6','a7'],
  ['h1','g2','f3','e4','d5','c6','b7','a8'],
     ['h2','g3','f4','e5','d6','c7','b8'],
       ['h3','g4','f5','e6','d7','c8'],
          ['h4','g5','f6','e7','d8'],
            ['h5','g6','f7','e8'],
               ['h6','g7','f8'],
                 ['h7','g8'],
                   ['h8']]



star_right =      [['h1'],
                 ['h2','g1'],
              ['h3','g2','f1'],
            ['h4','g3','f2','e1'],
          ['h5','g4','f3','e2','d1'],
        ['h6','g5','f4','e3','d2','c1'],
      ['h7','g6','f5','e4','d3','c2','b1'],
   ['h8','g7','f6','e5','d4','c3','b2','a1'],
      ['g8','f7','e6','d5','c4','b3','a2'],
        ['f8','e7','d6','c5','b4','a3'],
          ['e8','d7','c6','b5','a4'],
            ['d8','c7','b6','a5'],
               ['c8','b7','a6'],
                  ['b8','a7'],
                     ['a8']]



star_left =        [[1],         #CGA 1AVOIDING ROTATED BITBOARDS WITH DIRECT LOOKUPSam Tannous1Durham, North Carolina, USA
                   [2,9],       #https://arxiv.org/pdf/0704.3773.pdf
                 [3,10,17],
               [4,11,18,25],
              [5,12,19,26,33],
            [6,13,20,27,34,41],
           [7,14,21,28,35,42,49],
         [8,15,22,29,36,43,50,57],
          [16,23,30,37,44,51,58],
            [24,31,38,45,52,59],
              [32,39,46,53,60],
                [40,47,54,61],
                  [48,55,62],
                    [56,63],
                     [64]]





piboard = {'A8':'r','B8':'n','C8':'b','D8':'q','E8':'k','F8':'b','G8':'n','H8':'r',
           'A7':'p','B7':'p','C7':'p','D7':'p','E7':'p','F7':'p','G7':'p','H7':'p',
           'A6':'.','B6':'.','C6':'.','D6':'.','E6':'.','F6':'.','G6':'.','H6':'.',
           'A5':'.','B5':'.','C5':'.','D5':'.','E5':'.','F5':'.','G5':'.','H5':'.',
           'A4':'.','B4':'.','C4':'.','D4':'.','E4':'.','F4':'.','G4':'.','H4':'.',
           'A3':'.','B3':'.','C3':'.','D3':'.','E3':'.','F3':'.','G3':'.','H3':'.',
           'A2':'P','B2':'P','C2':'P','D2':'P','E2':'P','F2':'P','G2':'P','H2':'P',
           'A1':'R','B1':'N','C1':'B','D1':'Q','E1':'K','F1':'B','G1':'N','H1':'R',
}
one_to_64 = np.arange(1,65).reshape(8, 8)[::-1]
one_to_120 = np.arange(0,120).reshape(12,10)[::-1]
one_to_144 = np.arange(0,144).reshape(12,12)[::-1]
print(one_to_144)


ones = np.ones((8,8), dtype=np.uint8)
zeros  = np.zeros((8,8),dtype=np.uint8)
board  = np.zeros((8,8),dtype=np.uint8)
board[1::2,::2] = 1
board[::2,1::2] = 1
Filo = ["a", "b", "c", "d", "e", "f", "g", "h"]
Numbr = ["1", "2", "3", "4", "5", "6", "7", "8"]

filonum = [n+f for f in Numbr for n in Filo]
filonum = np.array(filonum, dtype = np.chararray).reshape(8,8)[::-1]


SQUARES ={'A8':110,'B8':111,'C8':112,'D8':113,'E8':114,'F8':115,'G8':116,'H8':117,
          'A7':98,'B7':99,'C7':100,'D7':101,'E7':102,'F7':103,'G7':104,'H7':105,
          'A6':86,'B6':87,'C6':88,'D6':89,'E6':90,'F6':91,'G6':92,'H6':93,
          'A5':74,'B5':75,'C5':76,'D5':77,'E5':78,'F5':79,'G5':80,'H5':81,
          'A4':62,'B4':63,'C4':64,'D4':65,'E4':66,'F4':67,'G4':68,'H4':69,
          'A3':50,'B3':51,'C3':52,'D3':53,'E3':54,'F3':55,'G3':56,'H3':57,
          'A2':38,'B2':39,'C2':40,'D2':41,'E2':42,'F2':43,'G2':44,'H2':45,
          'A1':26,'B1':27,'C1':28,'D1':29,'E1':30,'F1':31,'G1':32,'H1':33,}

outofboard = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,
             22,23,120,121,122,123,124,125,126,127,128,129,130,131,
             132,133,134,135,136,137,138,139,140,141,142,143,108,109,
             96,97,84,85,72,73,60,61,48,49,36,37,24,25,34,35,46,47,58,
             59,70,71,82,83,94,95,106,107,118,119]
print(len(outofboard))

[[132 133 134 135 136 137 138 139 140 141 142 143]
 [120 121 122 123 124 125 126 127 128 129 130 131]
 [108 109 110 111 112 113 114 115 116 117 118 119]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [  0   1   2   3   4   5   6   7   8   9  10  11]]
80


In [12]:
def zuege():
    zug = 0
    

In [13]:
x = [['br','bn','bb','bq','bk','bb','bn','br'],
                 ['bp','bp','bp','bp','bp','bp','bp','bp'],
                 ['','','','','','','',''],
                 ['','','','','','','',''],
                 ['','','','','','','',''],
                 ['','','','','','','',''],
                 ['wp','wp','wp','wp','wp','wp','wp','wp'],
                 ['wr','wn','wb','wq','wk','wb','wn','wr']]
import numpy as np
x = np.reshape(x,(15,(1,2,3,4,5,6,7,8,7,6,5,4,3,2,1)))
print(x)

TypeError: 'tuple' object cannot be interpreted as an integer